baseURL: 'https://blog.zatamine.com/'
languageCode: 'en-us'
title: zatamine's blog
theme: 'PaperMod'
pagenate: '5'

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true


params:
  subtitle: zatamine's blog
  title: Amine's blog
  description: "Software Engineering life"
  keywords: [Software, Engineering, development]
  author: Me

menus:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 100
    - identifier: posts
      name: Posts 
      url: /posts/
      weight: 200
