baseURL = 'https://zatamine.com/'
languageCode = 'en-us'
title = 'Amine — Independent Software Engineer & SRE'
theme = 'zatamine'

[params]
    description = "High-throughput Go Backend Development, SRE, DevOps & Automation."
    email = "hello@zatamine.com"
    github = "https://github.com/zatamine"
    twitter = "https://x.com/zatamine"
    linkedin = "https://linkedin.com/in/zatamine"

[taxonomies]
    tag = "tags"
    category = "categories"

[markup]
    [markup.highlight]
        codeFences = true
        noClasses = false
        style = "monokai"
        lineNos = true
        noTrimRights = false

[[languages]]
    languageName = 'English'
    weight = 1
