# Default configuration for the theme (to be used as example in documentation)
# This file should not be modified by users, but can be used to understand defaults.

baseURL = 'https://example.com'
languageCode = 'en-US'
title = 'Zatamine Theme Demo'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
