baseURL = '/'
languageCode = 'en-us'
title = 'Amine — Independent SRE & Software Engineer'
theme = 'zatamine'

[params]
  description = "High-throughput Go Backend Development, site reliability engineering (SRE), DevOps, and automation."
  email = "hello@zatamine.com"
  github = "https://github.com/zatamine"
  twitter = "https://x.com/zatamine"
  linkedin = "https://linkedin.com/in/zatamine"

[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
  [markup.highlight]
    codeFences = true
    noClasses = false
    style = "monokai"
    lineNos = true
    noTrimRights = false

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]

[params.assets]
  css = ["main.css"]